# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orbs:
  slack: circleci/slack@4.12.1

jobs:
  check-package-version:
    docker:
      - image: cimg/openjdk:17.0.3
    steps:
      - checkout
      - run:
          name: Check version has been bumped
          command: |
            bash ./scripts/check-package-version.sh $CIRCLE_PROJECT_REPONAME
            package_version=$(mvn -s .circleci/settings.xml -f pom.xml -q -Dexec.executable="echo" \
                                  -Dexec.args='${project.version}' --non-recursive exec:exec)
            echo "package version config" $package_version
            echo "export PACKAGE_VERSION='$package_version'" >> $BASH_ENV
            source $BASH_ENV
      - persist_to_workspace:
          root: ~/project
          paths:
            - .
      - attach_workspace:
          at: ~/project/
      - slack/notify:
          channel: $SLACK_DEFAULT_CHANNEL
          event: fail
          template: basic_fail_1
      - slack/notify:
          channel: $SLACK_DEFAULT_CHANNEL
          event: pass
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "plain_text",
                      "text": "Package Versions: ${PACKAGE_VERSION}",
                      "emoji": true
                    }
                  ]
                }
              ]
            }

  validate:
    docker:
      - image: cimg/openjdk:17.0.3
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          command: |
            mvn clean validate compile
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
      - persist_to_workspace:
          root: ~/project
          paths:
            - .
      - slack/notify:
          channel: $SLACK_DEFAULT_CHANNEL
          event: fail
          template: basic_fail_1

  pack:
    docker:
      - image: cimg/openjdk:17.0.3
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          command: |
            mvn package
      - persist_to_workspace:
          root: ~/project
          paths:
            - .
      - slack/notify:
          channel: $SLACK_DEFAULT_CHANNEL
          event: fail
          template: basic_fail_1


  build:
    docker:
      - image: cimg/openjdk:17.0.3
    steps:
      - checkout
      - run:
          command: |
            mvn clean install
            echo 'export COMMIT_MESSAGE=$(git log -1 --pretty=format:"%s")' >> $BASH_ENV
            source $BASH_ENV
      - slack/notify:
          channel: $SLACK_DEFAULT_CHANNEL
          event: fail
          template: basic_fail_1
      - slack/notify:
          channel: $SLACK_DEFAULT_CHANNEL
          event: pass
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "plain_text",
                      "text": "Commit messages:  $COMMIT_MESSAGE :white_check_mark:",
                      "emoji": true
                    }
                  ]
                }
              ]
            }
      - slack/notify:
          channel: $SLACK_DEFAULT_CHANNEL
          event: pass
          template: basic_success_1

  deploy:
    docker:
      - image: cimg/openjdk:17.0.3
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Publish package
          command: |
            mvn -s .circleci/settings.xml deploy
            rm -f ~/version.txt
      - slack/notify:
          channel: $SLACK_DEFAULT_CHANNEL
          event: fail
          template: basic_fail_1
      - slack/notify:
          channel: $SLACK_DEFAULT_CHANNEL
          event: pass
          template: success_tagged_deploy_1

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - validate
      - check-package-version:
          filters:
            branches:
              ignore:
                - main
      - pack:
          requires:
            - validate
            - check-package-version
      - build:
          requires:
            - pack
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: /^(main|verify)$/
